// <auto-generated>
//   Generated by interoptopus via `cargo test -p nordocs-ffi generate_csharp_binding`.
//   DO NOT EDIT — regenerate instead; CI fails if this file is stale.
// </auto-generated>

#pragma warning disable 0105
using System;
using System.Collections;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using Nordocs.Ffi;
#pragma warning restore 0105

namespace Nordocs.Ffi
{
    public static partial class NordocsFfi
    {
        public const string NativeLib = "nordocs";

        static NordocsFfi()
        {
        }


        /// Free a [`ByteBuffer`] returned by this library.
        ///
        /// Single-call: see the ownership rules on the [module docs](self). Passing the
        /// empty buffer (null pointer) is a no-op. Panics during free are swallowed so
        /// nothing unwinds across the ABI.
        [DllImport(NativeLib, CallingConvention = CallingConvention.Cdecl, EntryPoint = "ndoc_byte_buffer_free")]
        public static extern void ndoc_byte_buffer_free(ByteBuffer buffer);

        /// Free an [`FfiString`] returned by this library.
        ///
        /// Single-call: see the ownership rules on the [module docs](self). Passing the
        /// empty string (null pointer) is a no-op. Panics during free are swallowed so
        /// nothing unwinds across the ABI.
        [DllImport(NativeLib, CallingConvention = CallingConvention.Cdecl, EntryPoint = "ndoc_string_free")]
        public static extern void ndoc_string_free(FfiString s);

        /// Free the message owned by an [`FfiError`].
        ///
        /// Single-call, like the other free exports. Passing an `Ok` error (empty
        /// message) is a no-op.
        [DllImport(NativeLib, CallingConvention = CallingConvention.Cdecl, EntryPoint = "ndoc_error_free")]
        public static extern void ndoc_error_free(FfiError error);

        /// Compile raw Typst markup to PDF bytes, with optional `sys.inputs`.
        ///
        /// `vars` is a JSON object of `sys.inputs` values (or null/empty for none).
        /// Mirrors the reference `ITypstCompiler.CompileToPdf`. On failure returns the
        /// empty buffer and sets `out_err`.
        [DllImport(NativeLib, CallingConvention = CallingConvention.Cdecl, EntryPoint = "ndoc_compile_to_pdf")]
        public static extern ByteBuffer ndoc_compile_to_pdf(string source, string vars, out FfiError out_err);

        /// Compile the document at `path` to PDF bytes (path form).
        ///
        /// Mirrors the reference `ITypstCompiler.CompileFileToPdf`; routing by file shape
        /// (`.md`, `.ndoc.typ`, raw Typst) is the engine's. On failure returns the empty
        /// buffer and sets `out_err`.
        [DllImport(NativeLib, CallingConvention = CallingConvention.Cdecl, EntryPoint = "ndoc_compile_file_to_pdf")]
        public static extern ByteBuffer ndoc_compile_file_to_pdf(string path, out FfiError out_err);

        /// Compile to a multi-format [`CompileResult`].
        ///
        /// `vars` is a JSON object of `sys.inputs` values (or null/empty for none).
        /// `dpi` is the PNG render resolution (ignored for PDF/SVG). For SVG/PNG the
        /// result holds one buffer per page; for PDF, a single buffer. On failure returns
        /// an empty result of the requested format and sets `out_err`.
        [DllImport(NativeLib, CallingConvention = CallingConvention.Cdecl, EntryPoint = "ndoc_compile")]
        public static extern CompileResult ndoc_compile(string source, string vars, FfiFormat format, float dpi, out FfiError out_err);

        /// Free a [`CompileResult`] returned by [`ndoc_compile`].
        ///
        /// Single-call: frees every inner [`ByteBuffer`] and the backing array. Passing
        /// an empty result (null `buffers`) is a no-op. Panics during free are swallowed
        /// so nothing unwinds across the ABI.
        [DllImport(NativeLib, CallingConvention = CallingConvention.Cdecl, EntryPoint = "ndoc_compile_result_free")]
        public static extern void ndoc_compile_result_free(CompileResult result);

        /// Convert Markdown content to Typst markup.
        ///
        /// Mirrors the reference `IMarkdownToTypstConverter.Convert`. On failure returns
        /// the empty string and sets `out_err`.
        [DllImport(NativeLib, CallingConvention = CallingConvention.Cdecl, EntryPoint = "ndoc_markdown_to_typst")]
        public static extern FfiString ndoc_markdown_to_typst(string markdown, out FfiError out_err);

        /// Render a single component to PDF for live preview (the
        /// `IPreviewRenderer.RenderComponentPreview` surface).
        ///
        /// `schema` is the component's [`ComponentSchema`] as JSON; `input_values` is a
        /// JSON object of author-supplied overrides; `theme_code` is an optional theme
        /// (null uses the engine's minimal theme). On failure returns the empty buffer
        /// and sets `out_err`.
        [DllImport(NativeLib, CallingConvention = CallingConvention.Cdecl, EntryPoint = "ndoc_render_component_preview")]
        public static extern ByteBuffer ndoc_render_component_preview(string component_source, string schema, string input_values, string theme_code, out FfiError out_err);

        /// Render a complete document to PDF for live preview (the
        /// `IPreviewRenderer.RenderDocumentPreview` surface).
        ///
        /// `state` is the [`Document`] as JSON; `component_sources` is a JSON object of
        /// `name -> Typst source`; `component_schemas` is a JSON object of
        /// `name -> ComponentSchema`. On failure returns the empty buffer and sets
        /// `out_err`.
        [DllImport(NativeLib, CallingConvention = CallingConvention.Cdecl, EntryPoint = "ndoc_render_document_preview")]
        public static extern ByteBuffer ndoc_render_document_preview(string state, string theme_code, string component_sources, string component_schemas, out FfiError out_err);

        /// Create a new, empty entry-format `.ndoc.typ` document at `path`.
        [DllImport(NativeLib, CallingConvention = CallingConvention.Cdecl, EntryPoint = "ndoc_create_document")]
        public static extern void ndoc_create_document(string path, out FfiError out_err);

        /// Append an entry (`kind` is `"component"` or `"template"`) to an entry-format
        /// document.
        [DllImport(NativeLib, CallingConvention = CallingConvention.Cdecl, EntryPoint = "ndoc_add_entry")]
        public static extern void ndoc_add_entry(string path, string name, string kind, string content, out FfiError out_err);

        /// Replace the content of the named entry in an entry-format document.
        [DllImport(NativeLib, CallingConvention = CallingConvention.Cdecl, EntryPoint = "ndoc_edit_entry")]
        public static extern void ndoc_edit_entry(string path, string name, string content, out FfiError out_err);

        /// Read the structured [`Document`] persisted in a four-section authoring file,
        /// returned as JSON.
        ///
        /// This is the read half of the `doc` node-tree round-trip: a host reads the
        /// document, mutates the JSON tree (the `doc new`/`add`/`set`/`remove`
        /// operations), and writes it back with [`ndoc_write_document`].
        [DllImport(NativeLib, CallingConvention = CallingConvention.Cdecl, EntryPoint = "ndoc_read_document")]
        public static extern FfiString ndoc_read_document(string path, out FfiError out_err);

        /// Persist a structured [`Document`] (`doc_json`) into a four-section authoring
        /// file, preserving its other sections.
        [DllImport(NativeLib, CallingConvention = CallingConvention.Cdecl, EntryPoint = "ndoc_write_document")]
        public static extern void ndoc_write_document(string path, string doc_json, out FfiError out_err);

        /// Embed `image_bytes` (named `image_name`) into a four-section document.
        ///
        /// Returns a JSON object `{ "status": "added" | "already_present", "hash": ... }`
        /// describing the (idempotent) outcome.
        [DllImport(NativeLib, CallingConvention = CallingConvention.Cdecl, EntryPoint = "ndoc_embed_image")]
        public static extern FfiString ndoc_embed_image(string path, string image_name, Sliceu8 image_bytes, out FfiError out_err);

        /// Embed `image_bytes` (named `image_name`) into a four-section document.
        ///
        /// Returns a JSON object `{ "status": "added" | "already_present", "hash": ... }`
        /// describing the (idempotent) outcome.
        public static FfiString ndoc_embed_image(string path, string image_name, byte[] image_bytes, out FfiError out_err)
        {
            var image_bytes_pinned = GCHandle.Alloc(image_bytes, GCHandleType.Pinned);
            var image_bytes_slice = new Sliceu8(image_bytes_pinned, (ulong) image_bytes.Length);
            try
            {
                return ndoc_embed_image(path, image_name, image_bytes_slice, out out_err);;
            }
            finally
            {
                image_bytes_pinned.Free();
            }
        }

        /// Validate a `.ndoc.typ` or `.md` document, returning the result as JSON.
        ///
        /// The JSON shape matches the CLI `--json` envelope's payload:
        /// `{ "violations": [...], "summary": ... | null, "valid": bool }`.
        [DllImport(NativeLib, CallingConvention = CallingConvention.Cdecl, EntryPoint = "ndoc_validate_file")]
        public static extern FfiString ndoc_validate_file(string path, out FfiError out_err);

        /// Parse a `.ncmp.typ` component file, returning its [`ComponentSchema`] as JSON.
        [DllImport(NativeLib, CallingConvention = CallingConvention.Cdecl, EntryPoint = "ndoc_component_schema")]
        public static extern FfiString ndoc_component_schema(string path, out FfiError out_err);

        /// Parse a `.ndoct.typ` template file, returning its `TemplateSchema` as JSON.
        [DllImport(NativeLib, CallingConvention = CallingConvention.Cdecl, EntryPoint = "ndoc_template_schema")]
        public static extern FfiString ndoc_template_schema(string path, out FfiError out_err);

        /// Return the built-in component/template [`Catalogue`] as JSON.
        [DllImport(NativeLib, CallingConvention = CallingConvention.Cdecl, EntryPoint = "ndoc_catalogue")]
        public static extern FfiString ndoc_catalogue(out FfiError out_err);

        /// Load item collections from `dir`, returning a JSON summary.
        ///
        /// The JSON shape matches the CLI `item load --json` payload:
        /// `{ "collections": [ { "collection": name, "items": count }, ... ] }`.
        [DllImport(NativeLib, CallingConvention = CallingConvention.Cdecl, EntryPoint = "ndoc_item_collections")]
        public static extern FfiString ndoc_item_collections(string dir, out FfiError out_err);

        /// Compile a source into an opaque session handle (multi-format + source map).
        ///
        /// `vars` is a JSON object of `sys.inputs` values (or null/empty for none).
        /// Returns a non-null handle the caller owns on success; on failure returns null
        /// and sets `out_err`.
        [DllImport(NativeLib, CallingConvention = CallingConvention.Cdecl, EntryPoint = "ndoc_compile_session")]
        public static extern IntPtr ndoc_compile_session(string source, string vars, out FfiError out_err);

        /// Release a session handle returned by [`ndoc_compile_session`].
        ///
        /// Single-call. Passing a null handle is a no-op, so a wrapper that nulls its
        /// field after the first free is double-free safe. Panics during free are
        /// swallowed so nothing unwinds across the ABI.
        [DllImport(NativeLib, CallingConvention = CallingConvention.Cdecl, EntryPoint = "ndoc_session_free")]
        public static extern void ndoc_session_free(IntPtr handle);

        /// Number of laid-out pages in the session. Returns 0 and sets `out_err` on a
        /// null handle.
        [DllImport(NativeLib, CallingConvention = CallingConvention.Cdecl, EntryPoint = "ndoc_session_page_count")]
        public static extern ulong ndoc_session_page_count(IntPtr handle, out FfiError out_err);

        /// Size of the page at 0-based `index`, in points. Zeroed (and `out_err` set) when
        /// the handle is null or the index is out of range.
        [DllImport(NativeLib, CallingConvention = CallingConvention.Cdecl, EntryPoint = "ndoc_session_page_size")]
        public static extern FfiPageSize ndoc_session_page_size(IntPtr handle, ulong index, out FfiError out_err);

        /// Export the page at 0-based `page` to an SVG string. Empty (and `out_err` set)
        /// on failure.
        [DllImport(NativeLib, CallingConvention = CallingConvention.Cdecl, EntryPoint = "ndoc_session_svg")]
        public static extern FfiString ndoc_session_svg(IntPtr handle, ulong page, out FfiError out_err);

        /// Render the page at 0-based `page` to PNG bytes at `dpi`. Empty buffer (and
        /// `out_err` set) on failure.
        [DllImport(NativeLib, CallingConvention = CallingConvention.Cdecl, EntryPoint = "ndoc_session_png")]
        public static extern ByteBuffer ndoc_session_png(IntPtr handle, ulong page, float dpi, out FfiError out_err);

        /// Map a click on a rendered page back to its source location (backward map).
        ///
        /// `page` is 0-based; `x_pt`/`y_pt` are page-local coordinates in points. Returns
        /// a JSON-serialised `Jump` (or `null` when the click resolves to no target).
        [DllImport(NativeLib, CallingConvention = CallingConvention.Cdecl, EntryPoint = "ndoc_session_jump_from_click")]
        public static extern FfiString ndoc_session_jump_from_click(IntPtr handle, ulong page, double x_pt, double y_pt, out FfiError out_err);

        /// Map a source cursor to the on-page positions it produced (forward map).
        ///
        /// `file` is a virtual source path (the composed source is `main.typ`); `offset`
        /// is a byte offset into it. Returns a JSON array of `Position`s (empty array when
        /// the file is unknown or the cursor maps to no glyphs).
        [DllImport(NativeLib, CallingConvention = CallingConvention.Cdecl, EntryPoint = "ndoc_session_jump_from_cursor")]
        public static extern FfiString ndoc_session_jump_from_cursor(IntPtr handle, string file, ulong offset, out FfiError out_err);

    }

    /// The category of an FFI failure.
    ///
    /// `Ok` is the zero value (success); the remaining variants map one-for-one onto
    /// [`nordocs_core::Error`], and `Panic` marks a Rust panic caught at the
    /// boundary.
    public enum FfiErrorCode
    {
        /// No error.
        Ok = 0,
        /// `nordocs_core::Error::Authoring`.
        Authoring = 1,
        /// `nordocs_core::Error::Validation`.
        Validation = 2,
        /// `nordocs_core::Error::Schema`.
        Schema = 3,
        /// `nordocs_core::Error::Markdown`.
        Markdown = 4,
        /// `nordocs_core::Error::Compile`.
        Compile = 5,
        /// `nordocs_core::Error::FatFile`.
        FatFile = 6,
        /// `nordocs_core::Error::Io`.
        Io = 7,
        /// `nordocs_core::Error::Json`.
        Json = 8,
        /// A Rust panic was caught at the FFI boundary.
        Panic = 99,
    }

    /// The output format requested from [`ndoc_compile`].
    ///
    /// Mirrors the formats the engine's [`CompiledDoc`](nordocs_core::compiler::CompiledDoc)
    /// exports. `Pdf` yields a single buffer; `Svg`/`Png` yield one buffer per page.
    public enum FfiFormat
    {
        /// A single PDF document buffer.
        Pdf = 0,
        /// One SVG document buffer per page.
        Svg = 1,
        /// One PNG image buffer per page.
        Png = 2,
    }

    /// An owned, heap-allocated byte buffer handed to the caller.
    ///
    /// Built from a `Vec<u8>` (e.g. PDF/SVG/PNG bytes from `nordocs-core`). Free it
    /// exactly once with [`ndoc_byte_buffer_free`].
    [Serializable]
    [StructLayout(LayoutKind.Sequential)]
    public partial struct ByteBuffer
    {
        /// Pointer to the first byte, or null when `len == 0`.
        public IntPtr data;
        /// Number of valid bytes. `u64` (not `usize`) for a fixed cross-platform ABI.
        public ulong len;
        /// Backing allocation capacity (the `Vec` capacity); needed to free safely.
        public ulong capacity;
    }

    /// A multi-format compile result: the chosen `format` plus its output buffers.
    ///
    /// `buffers` points to `len` [`ByteBuffer`]s (one per page for SVG/PNG; one for
    /// PDF). The caller owns the whole result and MUST release it exactly once with
    /// [`ndoc_compile_result_free`], which frees every inner buffer and the backing
    /// array. `buffers` is null when `len == 0`.
    [Serializable]
    [StructLayout(LayoutKind.Sequential)]
    public partial struct CompileResult
    {
        /// The format the buffers are encoded in (echoes the requested format).
        public FfiFormat format;
        /// Pointer to the first [`ByteBuffer`], or null when `len == 0`.
        public IntPtr buffers;
        /// Number of buffers.
        public ulong len;
        /// Backing array capacity; needed to free safely.
        public ulong capacity;
    }

    /// A structured FFI error: a category code plus an owned UTF-8 message.
    ///
    /// On success, exports leave this as [`FfiError::ok`] (code [`FfiErrorCode::Ok`],
    /// empty message). On failure, `message` is a human-readable description owned by
    /// the caller, who MUST release it with [`ndoc_error_free`] (or
    /// [`ndoc_string_free`] on the `message` field). The empty `Ok` value needs no
    /// free.
    [Serializable]
    [StructLayout(LayoutKind.Sequential)]
    public partial struct FfiError
    {
        /// The failure category (`Ok` on success).
        public FfiErrorCode code;
        /// Owned, UTF-8, human-readable message (empty on success).
        public FfiString message;
    }

    /// The size of a page in typographic points (`pt`).
    ///
    /// Returned by [`ndoc_session_page_size`]; zeroed when the call fails.
    [Serializable]
    [StructLayout(LayoutKind.Sequential)]
    public partial struct FfiPageSize
    {
        /// Page width in points.
        public double width_pt;
        /// Page height in points.
        public double height_pt;
    }

    /// An owned, heap-allocated UTF-8 string handed to the caller.
    ///
    /// The bytes in `[data, data + len)` are guaranteed valid UTF-8. Free it exactly
    /// once with [`ndoc_string_free`].
    [Serializable]
    [StructLayout(LayoutKind.Sequential)]
    public partial struct FfiString
    {
        /// Pointer to the first UTF-8 byte, or null when `len == 0`.
        public IntPtr data;
        /// Number of UTF-8 bytes (not code points, not NUL-terminated). `u64` for a
        /// fixed cross-platform ABI.
        public ulong len;
        /// Backing allocation capacity; needed to free safely.
        public ulong capacity;
    }

    ///A pointer to an array of data someone else owns which may not be modified.
    [Serializable]
    [StructLayout(LayoutKind.Sequential)]
    public partial struct Sliceu8
    {
        ///Pointer to start of immutable data.
        IntPtr data;
        ///Number of elements.
        ulong len;
    }

    public partial struct Sliceu8 : IEnumerable<byte>
    {
        public Sliceu8(GCHandle handle, ulong count)
        {
            this.data = handle.AddrOfPinnedObject();
            this.len = count;
        }
        public Sliceu8(IntPtr handle, ulong count)
        {
            this.data = handle;
            this.len = count;
        }
        public byte this[int i]
        {
            get
            {
                if (i >= Count) throw new IndexOutOfRangeException();
                var size = Marshal.SizeOf(typeof(byte));
                var ptr = new IntPtr(data.ToInt64() + i * size);
                return Marshal.PtrToStructure<byte>(ptr);
            }
        }
        public byte[] Copied
        {
            get
            {
                var rval = new byte[len];
                for (var i = 0; i < (int) len; i++) {
                    rval[i] = this[i];
                }
                return rval;
            }
        }
        public int Count => (int) len;
        public IEnumerator<byte> GetEnumerator()
        {
            for (var i = 0; i < (int)len; ++i)
            {
                yield return this[i];
            }
        }
        IEnumerator IEnumerable.GetEnumerator()
        {
            return this.GetEnumerator();
        }
    }




    public class InteropException<T> : Exception
    {
        public T Error { get; private set; }

        public InteropException(T error): base($"Something went wrong: {error}")
        {
            Error = error;
        }
    }

}
