//! C# binding generation and reference-parity checks (task group 5).
//!
//! This module is compiled only under `#[cfg(test)]`. It hosts:
//!
//! - [`generate_csharp_binding`] — the generation entry point. Running
//!   `cargo test -p nordocs-ffi generate_csharp_binding` (re)writes the committed
//!   C# P/Invoke binding at `crates/nordocs-ffi/bindings/NordocsFfi.g.cs` from the
//!   [`crate::ffi_inventory`]. CI runs this test and then `git diff --exit-code`
//!   on the binding so the checked-in copy can never drift from the Rust surface.
//! - [`ffi_surface_covers_reference_interfaces`] — the parity test. It parses the
//!   reference C# interfaces under `.reference/src/` and asserts the exported FFI
//!   surface covers every operation, documenting intentional divergences inline.
//!
//! The hand-written `IDisposable` session wrapper lives beside the generated file
//! at `bindings/NordocsSession.cs` (it is not generated — it wraps the opaque
//! handle exports to give C# idiomatic `using var session = ...` ergonomics).

use std::path::{Path, PathBuf};

use interoptopus::util::NamespaceMappings;
use interoptopus::writer::IndentWriter;
use interoptopus::Interop;
use interoptopus_backend_csharp::overloads::DotNet;
use interoptopus_backend_csharp::{CSharpVisibility, Config, Generator};

/// The repository-relative directory the bindings are published to.
const BINDINGS_DIR: &str = "bindings";
/// The generated binding file name (the `.g.` marks it as generated output).
const GENERATED_FILE: &str = "NordocsFfi.g.cs";

/// Absolute path to `crates/nordocs-ffi`.
fn crate_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
}

/// Absolute path to the committed generated binding.
fn generated_binding_path() -> PathBuf {
    crate_dir().join(BINDINGS_DIR).join(GENERATED_FILE)
}

/// The C# backend configuration. Kept in one place so the generation test and any
/// future tooling agree on namespace, class, and DLL names.
///
/// `dll_name` is `nordocs`, matching the cdylib's `[lib] name` (so the binding
/// `DllImport`s `libnordocs.dylib` / `libnordocs.so` / `nordocs.dll`).
fn csharp_config() -> Config {
    Config {
        file_header_comment: "// <auto-generated>\n//   Generated by interoptopus via \
             `cargo test -p nordocs-ffi generate_csharp_binding`.\n//   DO NOT EDIT — \
             regenerate instead; CI fails if this file is stale.\n// </auto-generated>"
            .to_string(),
        class: "NordocsFfi".to_string(),
        dll_name: "nordocs".to_string(),
        namespace_mappings: NamespaceMappings::new("Nordocs.Ffi"),
        visibility_types: CSharpVisibility::ForcePublic,
        ..Config::default()
    }
}

/// Render the C# binding for the FFI inventory to a string.
fn render_binding() -> Result<String, interoptopus::Error> {
    let mut generator = Generator::new(csharp_config(), crate::ffi_inventory());
    generator.add_overload_writer(DotNet::new());
    let mut buffer: Vec<u8> = Vec::new();
    {
        let mut writer = IndentWriter::new(&mut buffer);
        generator.write_to(&mut writer)?;
    }
    Ok(String::from_utf8(buffer).expect("interoptopus emits valid UTF-8"))
}

/// Generation entry point: (re)write the committed C# binding.
///
/// This is intentionally a test so `cargo test` keeps the binding fresh and CI can
/// regenerate-then-diff. It writes deterministic output (the inventory is fixed),
/// so re-running it on an unchanged surface is a no-op for `git`.
#[test]
fn generate_csharp_binding() {
    let binding = render_binding().expect("the FFI inventory must render to C#");

    // Sanity-check the generated content before publishing it: the binding must
    // declare the interop class, bind the native library, and expose the core
    // compile entry point. This guards against emitting empty/garbage output.
    assert!(
        binding.contains("class NordocsFfi"),
        "binding must declare the interop class"
    );
    assert!(
        binding.contains("nordocs"),
        "binding must reference the `nordocs` native library"
    );
    assert!(
        binding.contains("ndoc_compile_to_pdf"),
        "binding must export the core compile entry point"
    );

    let path = generated_binding_path();
    std::fs::create_dir_all(path.parent().expect("binding path has a parent"))
        .expect("create bindings dir");
    std::fs::write(&path, binding.as_bytes()).expect("write generated binding");
}

/// Names of every function registered in the FFI inventory.
fn inventory_function_names() -> Vec<String> {
    crate::ffi_inventory()
        .functions()
        .iter()
        .map(|f| f.name().to_string())
        .collect()
}

/// Extract C# method names declared in a reference interface source file.
///
/// A declaration is an identifier immediately followed by `(`; comment lines
/// (`//` / `///`) are skipped so XML-doc examples like `<c>image()</c>` are not
/// mistaken for operations. Interface methods are PascalCase, so we keep only
/// identifiers whose first character is uppercase.
fn reference_method_names(source: &str) -> Vec<String> {
    let mut names = Vec::new();
    for line in source.lines() {
        let trimmed = line.trim_start();
        if trimmed.starts_with("//") {
            continue;
        }
        let Some(paren) = line.find('(') else {
            continue;
        };
        let ident: String = line[..paren]
            .chars()
            .rev()
            .take_while(|c| c.is_alphanumeric() || *c == '_')
            .collect::<Vec<_>>()
            .into_iter()
            .rev()
            .collect();
        if ident.chars().next().is_some_and(|c| c.is_ascii_uppercase()) {
            names.push(ident);
        }
    }
    names
}

/// Read a reference interface file from `.reference/src/`.
fn read_reference(file: &str) -> String {
    // CARGO_MANIFEST_DIR is `<repo>/crates/nordocs-ffi`; the reference tree is at
    // `<repo>/.reference/src`.
    let path = crate_dir()
        .parent()
        .and_then(Path::parent)
        .expect("repo root")
        .join(".reference/src")
        .join(file);
    std::fs::read_to_string(&path).unwrap_or_else(|e| panic!("read {}: {e}", path.display()))
}

/// Parity test: every operation of the reference `ITypstCompiler`,
/// `IPreviewRenderer`, and `IMarkdownToTypstConverter` interfaces is covered by an
/// exported FFI function.
///
/// The table below is the authoritative reference-op → FFI-export mapping. Each
/// row also records the intentional divergence (the FFI is C-ABI flat, so rich C#
/// types are marshalled as UTF-8/JSON), satisfying the "document divergences"
/// requirement of task 5.3.
///
/// Intentional divergences (shape, not capability):
/// - `CompileToPdf(source, Dictionary<string,string>? variables)` →
///   `ndoc_compile_to_pdf(source, vars)` where `vars` is a JSON object string of
///   `sys.inputs` (a `Dictionary` does not cross a flat C ABI cleanly).
/// - `RenderComponentPreview(source, ComponentSchema, Dictionary, theme)` and
///   `RenderDocumentPreview(DocumentState, theme, Dictionary, Dictionary)` →
///   `ndoc_render_component_preview` / `ndoc_render_document_preview` which take
///   the same inputs as JSON strings (the schema/state/dictionaries are the
///   serialisable `core-api` request shapes the CLI already uses).
/// - The reference returns `byte[]` directly; the FFI returns a `ByteBuffer`
///   (pointer + length) with a matching `free`, plus an out-param `FfiError`
///   instead of throwing — the hand-written C# wrapper restores the idiomatic
///   `byte[]`/exception surface.
#[test]
fn ffi_surface_covers_reference_interfaces() {
    // reference file, reference method, covering FFI export.
    let mapping: &[(&str, &str, &str)] = &[
        ("ITypstCompiler.cs", "CompileToPdf", "ndoc_compile_to_pdf"),
        (
            "ITypstCompiler.cs",
            "CompileFileToPdf",
            "ndoc_compile_file_to_pdf",
        ),
        (
            "IMarkdownToTypstConverter.cs",
            "Convert",
            "ndoc_markdown_to_typst",
        ),
        (
            "IPreviewRenderer.cs",
            "RenderComponentPreview",
            "ndoc_render_component_preview",
        ),
        (
            "IPreviewRenderer.cs",
            "RenderDocumentPreview",
            "ndoc_render_document_preview",
        ),
    ];

    let exported = inventory_function_names();

    // 1. Every mapped FFI export actually exists in the inventory.
    for (iface, method, ffi) in mapping {
        assert!(
            exported.iter().any(|f| f == ffi),
            "reference {iface}::{method} maps to FFI `{ffi}`, which is not exported"
        );
    }

    // 2. Every operation declared in each reference interface is covered by the
    //    mapping — so a new reference method fails this test until it is mapped to
    //    an FFI export (or explicitly recorded as a divergence above).
    for iface in [
        "ITypstCompiler.cs",
        "IPreviewRenderer.cs",
        "IMarkdownToTypstConverter.cs",
    ] {
        let source = read_reference(iface);
        for method in reference_method_names(&source) {
            assert!(
                mapping.iter().any(|(f, m, _)| *f == iface && *m == method),
                "reference {iface}::{method} is not covered by the FFI parity mapping"
            );
        }
    }
}
